<?php

namespace App\Ai\Providers;

use App\Ai\AiResponse;
use App\Contracts\AiServiceInterface;
use Throwable;

class FakeAiProvider implements AiServiceInterface
{
    /**
     * @var list<array<string, mixed>>
     */
    public static array $queue = [];

    public static ?Throwable $failWith = null;

    /**
     * @var list<array{system: string, prompt: string, options: array<string, mixed>}>
     */
    public static array $calls = [];

    public static function reset(): void
    {
        self::$queue = [];
        self::$failWith = null;
        self::$calls = [];
    }

    /**
     * @param  array<string, mixed>  $payload
     */
    public static function queue(array $payload): void
    {
        self::$queue[] = $payload;
    }

    public function complete(string $system, string $prompt, array $options = []): AiResponse
    {
        if (self::$failWith) {
            throw self::$failWith;
        }

        self::$calls[] = [
            'system' => $system,
            'prompt' => $prompt,
            'options' => $options,
        ];

        $data = array_shift(self::$queue) ?? $this->canned((string) ($options['task'] ?? 'generic'));

        return new AiResponse($data, 'fake', (string) ($options['model'] ?? 'fake-test'));
    }

    /**
     * @return array<string, mixed>
     */
    protected function canned(string $task): array
    {
        return match ($task) {
            'lead' => [
                'summary' => 'This lead is exploring a custom web application with an unclear budget.',
                'key_requirement' => 'A customer-facing web application',
                'business_need' => 'Capture and convert more qualified enquiries',
                'urgency' => 'medium',
                'risks' => ['Budget not confirmed', 'Decision maker not identified'],
                'suggested_status' => 'qualified',
                'next_follow_up' => 'Call this week to confirm budget, timeline, and decision maker.',
                'follow_up_message' => 'Hello, thank you for sharing your requirements. I would like to confirm budget, timeline, and the decision maker so we can prepare a focused proposal.',
            ],
            'requirement' => [
                'clarified_requirement' => 'The system should allow staff to capture the requirement, track approval, and confirm acceptance criteria before build.',
                'acceptance_criteria' => ['Staff can save the requirement', 'Client approval status is recorded', 'Attachments can be stored'],
                'missing_information' => ['Which roles can edit?', 'Are notifications required?'],
                'risks' => ['Scope may expand during approval'],
                'suggested_priority' => 'high',
            ],
            'quotation' => [
                'title' => 'Suggested delivery scope',
                'line_item_descriptions' => ['Discovery and solution design', 'Implementation of approved scope'],
                'missing_pricing_information' => ['Hourly or fixed-price preference', 'Number of revision rounds'],
                'payment_terms_wording' => '50% advance on acceptance, balance on delivery of the approved scope. This is suggested wording only; amounts are not generated by AI.',
            ],
            'project' => [
                'status_summary' => 'Delivery is active with a mix of open work and at least one risk to watch.',
                'overdue_tasks' => ['Review overdue tasks with owners'],
                'blocked_tasks' => ['Unblock tasks waiting on a decision'],
                'milestone_risks' => ['Upcoming milestones may slip if overdue work is not cleared'],
                'change_request_risks' => ['Pending change requests may affect cost and timeline'],
                'next_actions' => ['Review overdue work', 'Decide pending change requests'],
            ],
            'ticket' => [
                'conversation_summary' => 'The client reported an issue and is waiting for a staff reply.',
                'suggested_category' => 'General',
                'suggested_priority' => 'normal',
                'draft_reply' => 'Thank you for the update. We are reviewing this against the current project context and will share the next troubleshooting step shortly.',
                'troubleshooting_steps' => ['Confirm the latest client-visible symptom', 'Check related project status', 'Reply with the next action'],
            ],
            'finance' => [
                'overdue_patterns' => ['Some invoices are past due and need collection follow-up.'],
                'unusual_expenses' => ['Not enough historical expense data to identify unusual patterns.'],
                'receivables_summary' => 'Outstanding receivables should be reviewed by client and age.',
                'attention' => ['Follow up with clients that have overdue balances.'],
                'collection_suggestions' => ['Call the oldest overdue invoices first and confirm payment dates.'],
                'disclaimer' => 'These are operational suggestions for internal review, not accounting or legal advice.',
            ],
            'overview' => [
                'sales_risks' => ['Open pipeline may stall without follow-up.'],
                'project_risks' => ['Watch delayed or red-health projects.'],
                'finance_risks' => ['Outstanding and overdue invoices need collection attention.'],
                'support_risks' => ['Open or SLA-breached tickets need owners.'],
                'operational_items' => ['Review overdue work across sales, delivery, finance, and support.'],
                'suggested_actions' => ['Prioritize overdue invoices, blocked tasks, and breached tickets.'],
            ],
            default => [
                'summary' => 'Fake AI summary',
            ],
        };
    }
}
