<?php

return [
    'definitions' => [
        'crm.follow_up_due' => [
            'name' => 'CRM follow-up reminder',
            'description' => 'Notify assignees when a scheduled CRM follow-up reminder is due.',
            'module' => 'crm',
            'trigger_type' => 'schedule',
            'schedule' => 'hourly',
            'handler' => App\Automations\Handlers\CrmAutomations::class,
        ],
        'crm.lead_follow_up_upcoming' => [
            'name' => 'Upcoming lead follow-up',
            'description' => 'Remind owners of open leads whose next follow-up is approaching.',
            'module' => 'crm',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\CrmAutomations::class,
        ],
        'crm.lead_follow_up_overdue' => [
            'name' => 'Overdue lead follow-up',
            'description' => 'Remind owners of open leads whose next follow-up date has passed.',
            'module' => 'crm',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\CrmAutomations::class,
        ],
        'crm.quotation_follow_up' => [
            'name' => 'Quotation follow-up reminder',
            'description' => 'Remind sales staff about sent quotations still awaiting a decision.',
            'module' => 'crm',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\CrmAutomations::class,
        ],
        'projects.milestone_upcoming' => [
            'name' => 'Upcoming milestone deadline',
            'description' => 'Alert project managers when a milestone is due soon.',
            'module' => 'projects',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\ProjectAutomations::class,
        ],
        'projects.milestone_overdue' => [
            'name' => 'Overdue milestone',
            'description' => 'Alert project managers when a milestone is past due.',
            'module' => 'projects',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\ProjectAutomations::class,
        ],
        'projects.task_overdue' => [
            'name' => 'Overdue task',
            'description' => 'Notify assignees and managers about overdue tasks.',
            'module' => 'projects',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\ProjectAutomations::class,
        ],
        'projects.task_blocked' => [
            'name' => 'Blocked task alert',
            'description' => 'Notify assignees and managers about blocked tasks.',
            'module' => 'projects',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\ProjectAutomations::class,
        ],
        'projects.deadline_approaching' => [
            'name' => 'Project deadline approaching',
            'description' => 'Alert managers when an open project expected end date is approaching.',
            'module' => 'projects',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\ProjectAutomations::class,
        ],
        'projects.health_risk' => [
            'name' => 'Project health / risk alert',
            'description' => 'Alert managers when project health is yellow or red.',
            'module' => 'projects',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\ProjectAutomations::class,
        ],
        'projects.stage_overdue' => [
            'name' => 'Overdue project stage',
            'description' => 'Alert stage owners and project managers when a delivery stage is past due.',
            'module' => 'projects',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\ProjectAutomations::class,
        ],
        'projects.stage_activity' => [
            'name' => 'Project stage activity',
            'description' => 'Notify staff when a stage starts, is assigned, is ready for review, is approved, has changes requested, has new evidence or discussion, or is completed.',
            'module' => 'projects',
            'trigger_type' => 'event',
            'schedule' => null,
            'handler' => App\Automations\Handlers\ProjectAutomations::class,
        ],
        'finance.invoice_due' => [
            'name' => 'Invoice due reminder',
            'description' => 'Reuse finance reminder timing to notify staff of invoices due soon.',
            'module' => 'finance',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\FinanceAutomations::class,
        ],
        'finance.invoice_overdue' => [
            'name' => 'Invoice overdue reminder',
            'description' => 'Reuse existing overdue invoice reminder logic.',
            'module' => 'finance',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\FinanceAutomations::class,
        ],
        'finance.outstanding' => [
            'name' => 'Outstanding payment reminder',
            'description' => 'Remind finance staff about outstanding invoice balances.',
            'module' => 'finance',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\FinanceAutomations::class,
        ],
        'hr.leave_pending' => [
            'name' => 'Leave request pending approval',
            'description' => 'Remind approvers about pending leave requests.',
            'module' => 'hr',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\HrAutomations::class,
        ],
        'hr.employee_joining' => [
            'name' => 'Upcoming employee joining',
            'description' => 'Notify HR about employees whose joining date is approaching.',
            'module' => 'hr',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\HrAutomations::class,
        ],
        'hr.employee_exit' => [
            'name' => 'Upcoming employee exit',
            'description' => 'Notify HR about employees with an upcoming exit date.',
            'module' => 'hr',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\HrAutomations::class,
        ],
        'hr.document_alerts' => [
            'name' => 'HR document missing / expiring',
            'description' => 'Alert HR about pending or expiring employee documents. No salary data is included.',
            'module' => 'hr',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\HrAutomations::class,
        ],
        'support.sla_approaching' => [
            'name' => 'SLA approaching',
            'description' => 'Reuse existing support SLA approaching checks.',
            'module' => 'support',
            'trigger_type' => 'schedule',
            'schedule' => 'every_fifteen_minutes',
            'handler' => App\Automations\Handlers\SupportAutomations::class,
        ],
        'support.sla_breached' => [
            'name' => 'SLA breached',
            'description' => 'Reuse existing support SLA breach checks.',
            'module' => 'support',
            'trigger_type' => 'schedule',
            'schedule' => 'every_fifteen_minutes',
            'handler' => App\Automations\Handlers\SupportAutomations::class,
        ],
        'documents.expiry_approaching' => [
            'name' => 'Document expiry approaching',
            'description' => 'Reuse existing company document expiry warning logic.',
            'module' => 'documents',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\DocumentAutomations::class,
        ],
        'documents.expired' => [
            'name' => 'Document expired',
            'description' => 'Notify owners when a company document has passed its expiry date.',
            'module' => 'documents',
            'trigger_type' => 'schedule',
            'schedule' => 'daily',
            'handler' => App\Automations\Handlers\DocumentAutomations::class,
        ],
        'portal.ticket_activity' => [
            'name' => 'Client ticket activity',
            'description' => 'Notify client portal users about new tickets and public replies. Internal notes are never included.',
            'module' => 'portal',
            'trigger_type' => 'event',
            'schedule' => null,
            'handler' => App\Automations\Handlers\PortalAutomations::class,
        ],
        'portal.quotation_decision' => [
            'name' => 'Client quotation updates',
            'description' => 'Notify client portal users when a quotation is sent or decided.',
            'module' => 'portal',
            'trigger_type' => 'event',
            'schedule' => null,
            'handler' => App\Automations\Handlers\PortalAutomations::class,
        ],
        'portal.change_request' => [
            'name' => 'Client change-request status',
            'description' => 'Notify client portal users when a change request status changes.',
            'module' => 'portal',
            'trigger_type' => 'event',
            'schedule' => null,
            'handler' => App\Automations\Handlers\PortalAutomations::class,
        ],
        'portal.activity' => [
            'name' => 'Client project / document / invoice activity',
            'description' => 'Notify client portal users about relevant invoice, document, project, and stage activity. Internal notes are never included.',
            'module' => 'portal',
            'trigger_type' => 'event',
            'schedule' => null,
            'handler' => App\Automations\Handlers\PortalAutomations::class,
        ],
    ],
];
