<?php

return [
    'dashboard' => [
        ['name' => 'dashboard.view', 'description' => 'View the internal dashboard'],
    ],
    'users' => [
        ['name' => 'users.view', 'description' => 'View users'],
        ['name' => 'users.create', 'description' => 'Create users'],
        ['name' => 'users.edit', 'description' => 'Edit users'],
        ['name' => 'users.delete', 'description' => 'Delete users'],
    ],
    'roles' => [
        ['name' => 'roles.view', 'description' => 'View roles'],
        ['name' => 'roles.create', 'description' => 'Create roles'],
        ['name' => 'roles.edit', 'description' => 'Edit roles'],
        ['name' => 'roles.delete', 'description' => 'Delete roles'],
    ],
    'permissions' => [
        ['name' => 'permissions.view', 'description' => 'View permissions'],
    ],
    'sales' => [
        ['name' => 'sales.view', 'description' => 'View the sales dashboard'],
    ],
    'leads' => [
        ['name' => 'leads.view', 'description' => 'View leads'],
        ['name' => 'leads.create', 'description' => 'Create leads'],
        ['name' => 'leads.edit', 'description' => 'Edit leads'],
        ['name' => 'leads.delete', 'description' => 'Delete leads'],
        ['name' => 'leads.convert', 'description' => 'Convert leads into clients'],
    ],
    'clients' => [
        ['name' => 'clients.view', 'description' => 'View clients'],
        ['name' => 'clients.create', 'description' => 'Create clients'],
        ['name' => 'clients.edit', 'description' => 'Edit clients'],
        ['name' => 'clients.delete', 'description' => 'Delete clients'],
        ['name' => 'clients.manage_portal', 'description' => 'Manage client portal users'],
    ],
    'contacts' => [
        ['name' => 'contacts.view', 'description' => 'View contacts'],
        ['name' => 'contacts.create', 'description' => 'Create contacts'],
        ['name' => 'contacts.edit', 'description' => 'Edit contacts'],
        ['name' => 'contacts.delete', 'description' => 'Delete contacts'],
    ],
    'follow_ups' => [
        ['name' => 'follow_ups.view', 'description' => 'View follow-ups'],
        ['name' => 'follow_ups.create', 'description' => 'Create follow-ups'],
        ['name' => 'follow_ups.edit', 'description' => 'Edit follow-ups'],
        ['name' => 'follow_ups.delete', 'description' => 'Delete follow-ups'],
        ['name' => 'follow_ups.complete', 'description' => 'Complete follow-ups'],
    ],
    'quotations' => [
        ['name' => 'quotations.view', 'description' => 'View quotations'],
        ['name' => 'quotations.create', 'description' => 'Create quotations'],
        ['name' => 'quotations.edit', 'description' => 'Edit quotations'],
        ['name' => 'quotations.delete', 'description' => 'Delete quotations'],
        ['name' => 'quotations.send', 'description' => 'Send quotations'],
        ['name' => 'quotations.approve', 'description' => 'Accept or reject quotations'],
        ['name' => 'quotations.convert', 'description' => 'Convert accepted quotations'],
    ],
    'projects' => [
        ['name' => 'projects.view', 'description' => 'View projects'],
        ['name' => 'projects.create', 'description' => 'Create projects'],
        ['name' => 'projects.edit', 'description' => 'Edit projects'],
        ['name' => 'projects.delete', 'description' => 'Delete projects'],
        ['name' => 'projects.manage_team', 'description' => 'Manage project team members'],
        ['name' => 'projects.upload', 'description' => 'Upload and remove project files'],
        ['name' => 'projects.stages.view', 'description' => 'View project delivery stages'],
        ['name' => 'projects.stages.manage', 'description' => 'Create, edit, reorder and delete stages'],
        ['name' => 'projects.stages.assign', 'description' => 'Assign stage owners and members'],
        ['name' => 'projects.stages.submit_review', 'description' => 'Submit a stage for client review'],
        ['name' => 'projects.stages.complete', 'description' => 'Mark a stage as completed'],
        ['name' => 'projects.stage_evidence.view', 'description' => 'View stage work evidence'],
        ['name' => 'projects.stage_evidence.manage', 'description' => 'Add and remove stage work evidence'],
        ['name' => 'projects.stage_deliverables.view', 'description' => 'View stage deliverables'],
        ['name' => 'projects.stage_deliverables.manage', 'description' => 'Manage stage deliverables'],
        ['name' => 'projects.stage_reviews.view', 'description' => 'View stage review history'],
        ['name' => 'projects.stage_reviews.manage', 'description' => 'Manage stage submissions'],
        ['name' => 'projects.stage_discussion.view', 'description' => 'View stage discussions'],
        ['name' => 'projects.stage_discussion.create', 'description' => 'Post in stage discussions'],
        ['name' => 'projects.stage_approval.override', 'description' => 'Override incomplete submission or approval gates'],
    ],
    'milestones' => [
        ['name' => 'milestones.view', 'description' => 'View milestones'],
        ['name' => 'milestones.create', 'description' => 'Create milestones'],
        ['name' => 'milestones.edit', 'description' => 'Edit milestones'],
        ['name' => 'milestones.delete', 'description' => 'Delete milestones'],
    ],
    'tasks' => [
        ['name' => 'tasks.view', 'description' => 'View tasks'],
        ['name' => 'tasks.create', 'description' => 'Create tasks'],
        ['name' => 'tasks.edit', 'description' => 'Edit tasks'],
        ['name' => 'tasks.delete', 'description' => 'Delete tasks'],
    ],
    'requirements' => [
        ['name' => 'requirements.view', 'description' => 'View requirements'],
        ['name' => 'requirements.create', 'description' => 'Create requirements'],
        ['name' => 'requirements.edit', 'description' => 'Edit requirements'],
        ['name' => 'requirements.delete', 'description' => 'Delete requirements'],
        ['name' => 'requirements.approve', 'description' => 'Record client approval on requirements'],
    ],
    'change_requests' => [
        ['name' => 'change_requests.view', 'description' => 'View change requests'],
        ['name' => 'change_requests.create', 'description' => 'Create change requests'],
        ['name' => 'change_requests.edit', 'description' => 'Edit change requests'],
        ['name' => 'change_requests.delete', 'description' => 'Delete change requests'],
        ['name' => 'change_requests.approve', 'description' => 'Approve or reject change requests'],
    ],
    'invoices' => [
        ['name' => 'invoices.view', 'description' => 'View invoices'],
        ['name' => 'invoices.create', 'description' => 'Create invoices'],
        ['name' => 'invoices.edit', 'description' => 'Edit invoices'],
        ['name' => 'invoices.delete', 'description' => 'Delete invoices'],
        ['name' => 'invoices.send', 'description' => 'Send invoices'],
    ],
    'payments' => [
        ['name' => 'payments.view', 'description' => 'View payments'],
        ['name' => 'payments.create', 'description' => 'Create payments'],
        ['name' => 'payments.edit', 'description' => 'Edit payments'],
        ['name' => 'payments.delete', 'description' => 'Delete payments'],
    ],
    'expenses' => [
        ['name' => 'expenses.view', 'description' => 'View expenses'],
        ['name' => 'expenses.create', 'description' => 'Create expenses'],
        ['name' => 'expenses.edit', 'description' => 'Edit expenses'],
        ['name' => 'expenses.delete', 'description' => 'Delete expenses'],
    ],
    'finance' => [
        ['name' => 'finance.dashboard.view', 'description' => 'View the finance dashboard'],
        ['name' => 'finance.reports.view', 'description' => 'View finance reports and profitability'],
    ],
    'employees' => [
        ['name' => 'employees.view', 'description' => 'View employees'],
        ['name' => 'employees.create', 'description' => 'Create employees'],
        ['name' => 'employees.edit', 'description' => 'Edit employees'],
        ['name' => 'employees.delete', 'description' => 'Delete employees'],
    ],
    'employee_documents' => [
        ['name' => 'employee_documents.view', 'description' => 'View employee documents'],
        ['name' => 'employee_documents.upload', 'description' => 'Upload employee documents'],
        ['name' => 'employee_documents.delete', 'description' => 'Delete employee documents'],
    ],
    'leave' => [
        ['name' => 'leave.view', 'description' => 'View leave requests and balances'],
        ['name' => 'leave.create', 'description' => 'Create leave requests'],
        ['name' => 'leave.approve', 'description' => 'Approve leave requests'],
        ['name' => 'leave.reject', 'description' => 'Reject leave requests'],
    ],
    'assets' => [
        ['name' => 'assets.view', 'description' => 'View employee assets'],
        ['name' => 'assets.create', 'description' => 'Create employee assets'],
        ['name' => 'assets.assign', 'description' => 'Assign assets to employees'],
        ['name' => 'assets.return', 'description' => 'Mark assets as returned'],
    ],
    'onboarding' => [
        ['name' => 'onboarding.view', 'description' => 'View onboarding checklists'],
        ['name' => 'onboarding.manage', 'description' => 'Manage onboarding checklists'],
    ],
    'offboarding' => [
        ['name' => 'offboarding.view', 'description' => 'View offboarding checklists'],
        ['name' => 'offboarding.manage', 'description' => 'Manage offboarding checklists'],
    ],
    'hr' => [
        ['name' => 'hr.dashboard.view', 'description' => 'View the HR dashboard'],
    ],
    'payroll' => [
        ['name' => 'payroll.view', 'description' => 'View payroll and salary information'],
        ['name' => 'payroll.manage', 'description' => 'Manage payroll and salary information'],
    ],
    'tickets' => [
        ['name' => 'tickets.view', 'description' => 'View support tickets'],
        ['name' => 'tickets.create', 'description' => 'Create support tickets'],
        ['name' => 'tickets.edit', 'description' => 'Edit support tickets'],
        ['name' => 'tickets.delete', 'description' => 'Delete support tickets'],
        ['name' => 'tickets.assign', 'description' => 'Assign support tickets'],
        ['name' => 'tickets.reply', 'description' => 'Reply on support tickets'],
        ['name' => 'tickets.internal_notes', 'description' => 'View and write internal ticket notes'],
        ['name' => 'tickets.resolve', 'description' => 'Resolve support tickets'],
        ['name' => 'tickets.close', 'description' => 'Close support tickets'],
        ['name' => 'tickets.manage_categories', 'description' => 'Manage ticket categories'],
        ['name' => 'tickets.manage_sla', 'description' => 'Manage ticket SLA rules'],
    ],
    'support' => [
        ['name' => 'support.dashboard.view', 'description' => 'View the support dashboard'],
    ],
    'documents' => [
        ['name' => 'documents.view', 'description' => 'View company documents'],
        ['name' => 'documents.create', 'description' => 'Create company documents'],
        ['name' => 'documents.edit', 'description' => 'Edit company documents'],
        ['name' => 'documents.delete', 'description' => 'Delete company documents'],
        ['name' => 'documents.upload', 'description' => 'Upload company document files'],
        ['name' => 'documents.download', 'description' => 'Download company documents'],
        ['name' => 'documents.submit', 'description' => 'Submit company documents for review'],
        ['name' => 'documents.approve', 'description' => 'Approve or reject company documents'],
        ['name' => 'documents.archive', 'description' => 'Archive company documents'],
        ['name' => 'documents.manage_types', 'description' => 'Manage company document types'],
        ['name' => 'documents.manage_versions', 'description' => 'Create new company document versions'],
    ],
    'reports' => [
        ['name' => 'reports.view', 'description' => 'View the company reports overview'],
        ['name' => 'reports.sales.view', 'description' => 'View sales reports'],
        ['name' => 'reports.projects.view', 'description' => 'View project reports'],
        ['name' => 'reports.finance.view', 'description' => 'View finance reports'],
        ['name' => 'reports.hr.view', 'description' => 'View HR reports'],
        ['name' => 'reports.support.view', 'description' => 'View support reports'],
        ['name' => 'reports.export', 'description' => 'Export report data to CSV'],
    ],
    'ai' => [
        ['name' => 'ai.overview.view', 'description' => 'View the company AI risk summary'],
        ['name' => 'ai.leads.use', 'description' => 'Use the AI lead assistant'],
        ['name' => 'ai.requirements.use', 'description' => 'Use the AI requirement assistant'],
        ['name' => 'ai.quotations.use', 'description' => 'Use the AI quotation assistant'],
        ['name' => 'ai.projects.use', 'description' => 'Use the AI project assistant'],
        ['name' => 'ai.tickets.use', 'description' => 'Use the AI support assistant'],
        ['name' => 'ai.finance.use', 'description' => 'Use AI finance insights'],
    ],
    'automations' => [
        ['name' => 'automations.view', 'description' => 'View automations'],
        ['name' => 'automations.manage', 'description' => 'Enable, disable, and configure automations'],
        ['name' => 'automations.history.view', 'description' => 'View automation execution history'],
    ],
    'settings' => [
        ['name' => 'settings.view', 'description' => 'View settings'],
        ['name' => 'settings.manage', 'description' => 'Manage settings'],
    ],
    'audit_logs' => [
        ['name' => 'audit_logs.view', 'description' => 'View audit logs'],
    ],
];
