<?php

return [
    'cache_key' => 'dvmsoft.settings',
    'cache_ttl' => 3600,
    'branding_disk' => 'public',
    'branding_path' => 'branding',

    'definitions' => [
        'company.name' => [
            'type' => 'string',
            'group' => 'company',
            'description' => 'Legal or trading company name',
            'default' => 'Dvmsoft',
            'is_public' => true,
        ],
        'company.email' => [
            'type' => 'string',
            'group' => 'company',
            'description' => 'Primary company email address',
            'default' => 'hello@dvmsoft.com',
            'is_public' => true,
        ],
        'company.phone' => [
            'type' => 'string',
            'group' => 'company',
            'description' => 'Primary company phone number',
            'default' => '',
            'is_public' => true,
        ],
        'company.website' => [
            'type' => 'string',
            'group' => 'company',
            'description' => 'Company website URL',
            'default' => 'https://dvmsoft.com',
            'is_public' => true,
        ],
        'company.address' => [
            'type' => 'text',
            'group' => 'company',
            'description' => 'Registered company address',
            'default' => '',
            'is_public' => true,
        ],
        'company.gst_number' => [
            'type' => 'string',
            'group' => 'company',
            'description' => 'GST registration number',
            'default' => '',
            'is_public' => false,
        ],
        'company.pan_number' => [
            'type' => 'string',
            'group' => 'company',
            'description' => 'PAN number',
            'default' => '',
            'is_public' => false,
        ],
        'company.logo' => [
            'type' => 'file',
            'group' => 'branding',
            'description' => 'Company logo',
            'default' => '',
            'is_public' => true,
        ],
        'company.favicon' => [
            'type' => 'file',
            'group' => 'branding',
            'description' => 'Browser favicon',
            'default' => '',
            'is_public' => true,
        ],
        'company.currency' => [
            'type' => 'string',
            'group' => 'localization',
            'description' => 'Default currency code',
            'default' => 'INR',
            'is_public' => true,
        ],
        'company.timezone' => [
            'type' => 'string',
            'group' => 'localization',
            'description' => 'Default timezone',
            'default' => 'Asia/Kolkata',
            'is_public' => true,
        ],
        'company.date_format' => [
            'type' => 'string',
            'group' => 'localization',
            'description' => 'Display date format',
            'default' => 'd M Y',
            'is_public' => true,
        ],
        'email.from_name' => [
            'type' => 'string',
            'group' => 'email',
            'description' => 'Default outgoing email from name',
            'default' => 'Dvmsoft',
            'is_public' => false,
        ],
        'email.from_address' => [
            'type' => 'string',
            'group' => 'email',
            'description' => 'Default outgoing email from address',
            'default' => 'noreply@dvmsoft.com',
            'is_public' => false,
        ],
        'notifications.email_enabled' => [
            'type' => 'boolean',
            'group' => 'notifications',
            'description' => 'Send email notifications',
            'default' => true,
            'is_public' => false,
        ],
        'notifications.in_app_enabled' => [
            'type' => 'boolean',
            'group' => 'notifications',
            'description' => 'Show in-app notifications',
            'default' => true,
            'is_public' => false,
        ],
        'security.session_timeout' => [
            'type' => 'integer',
            'group' => 'security',
            'description' => 'Session lifetime in minutes',
            'default' => 120,
            'is_public' => false,
        ],
        'security.login_max_attempts' => [
            'type' => 'integer',
            'group' => 'security',
            'description' => 'Max failed login attempts per minute',
            'default' => 5,
            'is_public' => false,
        ],
        'security.require_strong_passwords' => [
            'type' => 'boolean',
            'group' => 'security',
            'description' => 'Enforce strong password rules',
            'default' => true,
            'is_public' => false,
        ],
        'system.maintenance_message' => [
            'type' => 'text',
            'group' => 'system',
            'description' => 'Optional maintenance banner message',
            'default' => '',
            'is_public' => false,
        ],
        'finance.invoice_prefix' => [
            'type' => 'string',
            'group' => 'finance',
            'description' => 'Invoice number prefix',
            'default' => 'INV',
            'is_public' => false,
        ],
        'finance.expense_prefix' => [
            'type' => 'string',
            'group' => 'finance',
            'description' => 'Expense number prefix',
            'default' => 'EXP',
            'is_public' => false,
        ],
        'finance.default_tax_percent' => [
            'type' => 'string',
            'group' => 'finance',
            'description' => 'Default GST / tax percent for invoices',
            'default' => '18',
            'is_public' => false,
        ],
        'finance.invoice_due_days' => [
            'type' => 'integer',
            'group' => 'finance',
            'description' => 'Default days until invoice due date',
            'default' => 15,
            'is_public' => false,
        ],
        'finance.bank_name' => [
            'type' => 'string',
            'group' => 'finance',
            'description' => 'Bank name for invoice payment details',
            'default' => '',
            'is_public' => false,
        ],
        'finance.bank_account_name' => [
            'type' => 'string',
            'group' => 'finance',
            'description' => 'Bank account holder name',
            'default' => '',
            'is_public' => false,
        ],
        'finance.bank_account_number' => [
            'type' => 'string',
            'group' => 'finance',
            'description' => 'Bank account number',
            'default' => '',
            'is_public' => false,
        ],
        'finance.bank_ifsc' => [
            'type' => 'string',
            'group' => 'finance',
            'description' => 'Bank IFSC / SWIFT code',
            'default' => '',
            'is_public' => false,
        ],
        'finance.upi_id' => [
            'type' => 'string',
            'group' => 'finance',
            'description' => 'UPI ID for collections',
            'default' => '',
            'is_public' => false,
        ],
        'finance.payment_instructions' => [
            'type' => 'text',
            'group' => 'finance',
            'description' => 'Additional payment instructions printed on invoices',
            'default' => '',
            'is_public' => false,
        ],
        'finance.reminder_days_before_due' => [
            'type' => 'integer',
            'group' => 'finance',
            'description' => 'Days before due date to send an upcoming reminder',
            'default' => 3,
            'is_public' => false,
        ],
        'finance.reminder_days_after_due' => [
            'type' => 'integer',
            'group' => 'finance',
            'description' => 'Minimum days between overdue reminders',
            'default' => 1,
            'is_public' => false,
        ],
        'hr.employee_prefix' => [
            'type' => 'string',
            'group' => 'hr',
            'description' => 'Employee code prefix',
            'default' => 'EMP',
            'is_public' => false,
        ],
        'hr.probation_days' => [
            'type' => 'integer',
            'group' => 'hr',
            'description' => 'Default probation period in days',
            'default' => 90,
            'is_public' => false,
        ],
        'hr.annual_leave_days' => [
            'type' => 'integer',
            'group' => 'hr',
            'description' => 'Default annual leave entitlement',
            'default' => 18,
            'is_public' => false,
        ],
        'support.ticket_prefix' => [
            'type' => 'string',
            'group' => 'support',
            'description' => 'Ticket number prefix',
            'default' => 'TKT',
            'is_public' => false,
        ],
        'documents.prefix' => [
            'type' => 'string',
            'group' => 'documents',
            'description' => 'Company document number prefix',
            'default' => 'DOC',
            'is_public' => false,
        ],
        'documents.expiry_warning_days' => [
            'type' => 'integer',
            'group' => 'documents',
            'description' => 'Days before expiry to warn owners',
            'default' => 30,
            'is_public' => false,
        ],
        'documents.version_format' => [
            'type' => 'string',
            'group' => 'documents',
            'description' => 'Version label format. Use {n} for the version number.',
            'default' => 'v{n}',
            'is_public' => false,
        ],
        'ai.enabled' => [
            'type' => 'boolean',
            'group' => 'ai',
            'description' => 'Enable AI assistance features',
            'default' => false,
            'is_public' => false,
        ],
        'ai.provider' => [
            'type' => 'string',
            'group' => 'ai',
            'description' => 'AI provider driver',
            'default' => 'openai',
            'is_public' => false,
        ],
        'ai.model' => [
            'type' => 'string',
            'group' => 'ai',
            'description' => 'AI model name',
            'default' => 'gpt-4o-mini',
            'is_public' => false,
        ],
        'ai.timeout' => [
            'type' => 'integer',
            'group' => 'ai',
            'description' => 'AI provider timeout in seconds',
            'default' => 20,
            'is_public' => false,
        ],
        'ai.max_tokens' => [
            'type' => 'integer',
            'group' => 'ai',
            'description' => 'Maximum tokens per AI response',
            'default' => 1200,
            'is_public' => false,
        ],
        'automations.enabled' => [
            'type' => 'boolean',
            'group' => 'automations',
            'description' => 'Enable the automation engine',
            'default' => true,
            'is_public' => false,
        ],
        'automations.lead_follow_up_upcoming_days' => [
            'type' => 'integer',
            'group' => 'automations',
            'description' => 'Days ahead to remind owners of upcoming lead follow-ups',
            'default' => 1,
            'is_public' => false,
        ],
        'automations.quotation_follow_up_days' => [
            'type' => 'integer',
            'group' => 'automations',
            'description' => 'Days after a quotation is sent before a follow-up reminder',
            'default' => 3,
            'is_public' => false,
        ],
        'automations.milestone_upcoming_days' => [
            'type' => 'integer',
            'group' => 'automations',
            'description' => 'Days ahead to warn about upcoming milestones',
            'default' => 3,
            'is_public' => false,
        ],
        'automations.project_deadline_days' => [
            'type' => 'integer',
            'group' => 'automations',
            'description' => 'Days ahead to warn about project deadlines',
            'default' => 7,
            'is_public' => false,
        ],
        'automations.hr_joining_days' => [
            'type' => 'integer',
            'group' => 'automations',
            'description' => 'Days ahead to notify HR about joining dates',
            'default' => 7,
            'is_public' => false,
        ],
        'automations.hr_exit_days' => [
            'type' => 'integer',
            'group' => 'automations',
            'description' => 'Days ahead to notify HR about exit dates',
            'default' => 7,
            'is_public' => false,
        ],
        'automations.hr_document_expiry_days' => [
            'type' => 'integer',
            'group' => 'automations',
            'description' => 'Days ahead to warn about HR document expiry',
            'default' => 30,
            'is_public' => false,
        ],
        'projects.default_client_approval_mode' => [
            'type' => 'string',
            'group' => 'projects',
            'description' => 'Default client approval mode for new projects (strict or flexible)',
            'default' => 'flexible',
            'is_public' => false,
        ],
    ],
];
